# Generated by Django 3.1.4 on 2020-12-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
