# Generated by Django 3.1.4 on 2020-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201208_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='necessary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='chessboard',
            field=models.CharField(default='00400040004000404000400040004000004000400040004040404040404040404040404040404040401040104010401010401040104010404010401040104010', max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='onTurn',
            field=models.BooleanField(default=False),
        ),
    ]
